// Catálogo com animes reais para demonstração do site.
// - "trailerQuery" abre a busca oficial do trailer no YouTube.
// - Apenas 1 item tem "completoUrl": é um anime real e de domínio público —
//   "A Espada Cega" (Namakura Gatana, 1917), a animação japonesa mais antiga
//   que se conhece — disponibilizada gratuita e oficialmente pelo Museu
//   Nacional de Arte Moderna de Tóquio / Arquivo Nacional de Filmes do Japão.
const CATALOGO_ANIMES = [
  {
    id: "a-espada-cega",
    titulo: "A Espada Cega",
    genero: "Comédia",
    ano: 1917,
    duracao: "4min",
    nota: 6.9,
    temporada: "Curta · único episódio",
    icon: "⚔️",
    cor1: "#a8a29e",
    cor2: "#1c1917",
    sinopse: "O anime mais antigo que se tem notícia: um samurai enganado compra uma espada sem fio e tenta, sem sucesso, usá-la contra moradores de sua cidade.",
    trailerQuery: "Namakura Gatana The Dull Sword 1917",
    completoUrl: "https://animation.filmarchives.jp/en/works/view/100183",
  },
  {
    id: "ataque-dos-titas",
    titulo: "Ataque dos Titãs",
    genero: "Ação",
    ano: 2013,
    duracao: "24min",
    nota: 9.0,
    temporada: "T1 · EP1",
    icon: "🧱",
    cor1: "#78350f",
    cor2: "#1a0d02",
    sinopse: "Nascida atrás de muralhas que protegem os últimos humanos de titãs devoradores de gente, uma geração de jovens soldados descobre que a verdade sobre o mundo é muito mais complexa do que aprenderam.",
    destaque: true,
    trailerQuery: "Attack on Titan trailer legendado",
  },
  {
    id: "demon-slayer",
    titulo: "Demon Slayer: Kimetsu no Yaiba",
    genero: "Fantasia",
    ano: 2019,
    duracao: "23min",
    nota: 8.8,
    temporada: "T1 · EP1",
    icon: "🗡️",
    cor1: "#16a34a",
    cor2: "#052e13",
    sinopse: "Depois que sua família é massacrada e sua irmã transformada em demônio, um jovem se torna caçador de demônios em busca de uma cura — e de vingança.",
    trailerQuery: "Demon Slayer trailer legendado",
  },
  {
    id: "jujutsu-kaisen",
    titulo: "Jujutsu Kaisen",
    genero: "Ação",
    ano: 2020,
    duracao: "24min",
    nota: 8.6,
    temporada: "T1 · EP1",
    icon: "👁️",
    cor1: "#7c3aed",
    cor2: "#190a33",
    sinopse: "Ao engolir um dedo amaldiçoado para proteger os colegas, um estudante colegial passa a abrigar um poderoso espírito amaldiçoado dentro do próprio corpo.",
    trailerQuery: "Jujutsu Kaisen trailer legendado",
  },
  {
    id: "spy-x-family",
    titulo: "Spy x Family",
    genero: "Comédia",
    ano: 2022,
    duracao: "24min",
    nota: 8.6,
    temporada: "T1 · EP1",
    icon: "🕵️",
    cor1: "#f472b6",
    cor2: "#330a1e",
    sinopse: "Um espião de elite precisa montar às pressas uma família falsa para uma missão — sem saber que a filha adotiva é telepata e a esposa, uma assassina profissional.",
    trailerQuery: "Spy x Family trailer legendado",
  },
  {
    id: "my-hero-academia",
    titulo: "My Hero Academia",
    genero: "Ação",
    ano: 2016,
    duracao: "24min",
    nota: 7.9,
    temporada: "T1 · EP1",
    icon: "💪",
    cor1: "#22c55e",
    cor2: "#062617",
    sinopse: "Em um mundo onde quase todos nascem com superpoderes, um garoto sem nenhum poder sonha em se tornar o maior herói de todos os tempos.",
    trailerQuery: "My Hero Academia trailer legendado",
  },
  {
    id: "your-name",
    titulo: "Your Name — Seu Nome",
    genero: "Romance",
    ano: 2016,
    duracao: "1h 46min",
    nota: 8.9,
    temporada: "Filme",
    icon: "🌌",
    cor1: "#f59e0b",
    cor2: "#331f03",
    sinopse: "Dois adolescentes de lugares completamente diferentes do Japão começam, misteriosamente, a trocar de corpo enquanto dormem — até que um encontro real entre os dois se torna urgente.",
    trailerQuery: "Your Name Kimi no Na wa trailer legendado",
  },
  {
    id: "steins-gate",
    titulo: "Steins;Gate",
    genero: "Ficção Científica",
    ano: 2011,
    duracao: "24min",
    nota: 9.0,
    temporada: "T1 · EP1",
    icon: "🔬",
    cor1: "#eab308",
    cor2: "#2e2404",
    sinopse: "Um grupo de amigos cria, por acaso, um aparelho capaz de enviar mensagens para o passado — e descobre que cada alteração na linha do tempo tem um preço.",
    trailerQuery: "Steins Gate trailer legendado",
  },
  {
    id: "clannad",
    titulo: "Clannad",
    genero: "Drama",
    ano: 2007,
    duracao: "23min",
    nota: 8.1,
    temporada: "T1 · EP1",
    icon: "🌸",
    cor1: "#fb923c",
    cor2: "#2c1304",
    sinopse: "Um estudante desmotivado com a própria vida começa a se envolver com os problemas e sonhos das garotas que conhece pela cidade, e aos poucos redescobre o que significa se importar com alguém.",
    trailerQuery: "Clannad anime trailer legendado",
  },
];
