// Catálogo com filmes reais para demonstração do site.
// - "trailerQuery" abre a busca oficial do trailer no YouTube (sempre funciona,
//   sem depender de um único ID de vídeo que pode ficar indisponível).
// - Apenas 1 item tem "completoEmbed": é um filme real e de domínio público
//   (Charade, 1963), hospedado oficialmente pelo Internet Archive — por isso
//   pode ser incorporado e assistido por completo, de graça e legalmente.
const CATALOGO_FILMES = [
  {
    id: "charade",
    titulo: "Charade",
    genero: "Comédia",
    ano: 1963,
    duracao: "1h 53min",
    nota: 7.9,
    icon: "🎩",
    cor1: "#d4af37",
    cor2: "#241d07",
    sinopse: "Recém-viúva em Paris, Regina descobre que o dinheiro roubado pelo marido despertou o interesse de homens perigosos — e do único estranho em quem ela acha que pode confiar.",
    destaque: false,
    trailerQuery: "Charade 1963 trailer",
    completoEmbed: "https://archive.org/embed/charade1963",
  },
  {
    id: "duna-parte-dois",
    titulo: "Duna: Parte Dois",
    genero: "Ficção Científica",
    ano: 2024,
    duracao: "2h 46min",
    nota: 8.5,
    icon: "🏜️",
    cor1: "#d97706",
    cor2: "#2b1704",
    sinopse: "Paul Atreides se une aos Fremen no deserto de Arrakis para enfrentar a Casa Harkonnen e vingar a queda de sua família, enquanto tenta escapar de um futuro que só ele consegue prever.",
    destaque: true,
    trailerQuery: "Duna Parte Dois trailer oficial legendado",
  },
  {
    id: "divertida-mente-2",
    titulo: "Divertida Mente 2",
    genero: "Animação",
    ano: 2024,
    duracao: "1h 36min",
    nota: 7.6,
    icon: "🎨",
    cor1: "#38bdf8",
    cor2: "#062233",
    sinopse: "Agora adolescente, Riley ganha novas emoções na sua mente — lideradas pela Ansiedade — que entram em choque com Alegria e as emoções originais pelo controle de suas decisões.",
    trailerQuery: "Divertida Mente 2 trailer oficial dublado",
  },
  {
    id: "oppenheimer",
    titulo: "Oppenheimer",
    genero: "Drama",
    ano: 2023,
    duracao: "3h 00min",
    nota: 8.3,
    icon: "☢️",
    cor1: "#f97316",
    cor2: "#230d02",
    sinopse: "A trajetória do físico J. Robert Oppenheimer, líder do Projeto Manhattan, e o peso moral de ter ajudado a criar a bomba atômica durante a Segunda Guerra Mundial.",
    trailerQuery: "Oppenheimer trailer oficial legendado",
  },
  {
    id: "corra",
    titulo: "Corra!",
    genero: "Terror",
    ano: 2017,
    duracao: "1h 44min",
    nota: 7.7,
    icon: "🌀",
    cor1: "#dc2626",
    cor2: "#1a0505",
    sinopse: "Um fotógrafo viaja para conhecer a família da namorada em uma casa isolada no interior — e aos poucos percebe que a hospitalidade esconde algo muito mais sinistro.",
    trailerQuery: "Corra Get Out trailer legendado",
  },
  {
    id: "top-gun-maverick",
    titulo: "Top Gun: Maverick",
    genero: "Ação",
    ano: 2022,
    duracao: "2h 11min",
    nota: 8.2,
    icon: "✈️",
    cor1: "#0ea5e9",
    cor2: "#031627",
    sinopse: "Décadas depois dos eventos do primeiro filme, o piloto Maverick é convocado para treinar uma nova geração de aviadores de elite para uma missão quase impossível.",
    trailerQuery: "Top Gun Maverick trailer oficial legendado",
  },
  {
    id: "a-origem",
    titulo: "A Origem",
    genero: "Ficção Científica",
    ano: 2010,
    duracao: "2h 28min",
    nota: 8.8,
    icon: "🌀",
    cor1: "#6366f1",
    cor2: "#0c0b28",
    sinopse: "Um ladrão especializado em roubar segredos durante o sono recebe a missão inversa: implantar uma ideia na mente de alguém sem que a pessoa perceba.",
    trailerQuery: "Inception A Origem trailer legendado",
  },
  {
    id: "de-volta-para-o-futuro",
    titulo: "De Volta Para o Futuro",
    genero: "Comédia",
    ano: 1985,
    duracao: "1h 56min",
    nota: 8.5,
    icon: "⏱️",
    cor1: "#f43f5e",
    cor2: "#2b0713",
    sinopse: "Um adolescente é acidentalmente enviado 30 anos ao passado em um carro modificado por seu amigo cientista — e precisa garantir que seus próprios pais se apaixonem, ou deixará de existir.",
    trailerQuery: "De Volta Para o Futuro trailer dublado",
  },
];
